# Generated by Django 2.0.5 on 2018-06-19 11:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBlog.Author_bio'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateField(default=datetime.date(2018, 6, 19)),
        ),
    ]
