# Generated by Django 2.0.5 on 2018-06-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBlog', '0002_auto_20180619_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-Date']},
        ),
        migrations.AddField(
            model_name='blog',
            name='Photo',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
