# Generated by Django 2.0.5 on 2018-06-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBlog', '0003_auto_20180619_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Photo',
        ),
        migrations.AddField(
            model_name='author_bio',
            name='Photo',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
