# Generated by Django 2.0.5 on 2018-06-20 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBlog', '0004_auto_20180619_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateField(default=datetime.date(2018, 6, 20)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='Comment',
            field=models.TextField(help_text='Enter Comments', max_length=500),
        ),
    ]
